-- OTB Property Command — Supabase security model SNAPSHOT (audit L16).
-- ----------------------------------------------------------------------------
-- This file version-controls the RLS/security posture so it is reviewable and
-- reproducible from the repo. It is a SNAPSHOT generated by live introspection
-- on 2026-07-10, NOT a migration runner. The authoritative migration history
-- lives in Supabase (project kbhsghodquchkgfdzckc); apply changes there via the
-- MCP `apply_migration` and re-snapshot this file. Migration list at bottom.
--
-- Roles (public.profiles.role): operator (full) · owner (read-oriented) ·
-- vendor (own folder only) · pending (no access). New sign-ins resolve in
-- handle_new_user(): vendor-roster email > authorized_emails allowlist > pending.
-- ============================================================================

-- ── SECURITY DEFINER helper functions (all pin search_path=public; each only
--    returns facts about the CALLER, so the anon/authenticated RPC-exposure
--    advisor WARNs are accepted) ──────────────────────────────────────────────

CREATE OR REPLACE FUNCTION public.is_operator()
 RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path TO 'public'
AS $$ select exists (select 1 from public.profiles where id = auth.uid() and role = 'operator'); $$;

CREATE OR REPLACE FUNCTION public.is_owner_or_operator()
 RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path TO 'public'
AS $$ select exists (select 1 from public.profiles where id = auth.uid() and role in ('owner','operator')); $$;

CREATE OR REPLACE FUNCTION public.is_vendor()
 RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path TO 'public'
AS $$ select exists (select 1 from public.profiles where id = auth.uid() and role = 'vendor'); $$;

CREATE OR REPLACE FUNCTION public.current_vendor_id()
 RETURNS text LANGUAGE sql STABLE SECURITY DEFINER SET search_path TO 'public'
AS $$
  select v.id from public.vendors v
  join public.profiles p on lower(p.email) = v.email
  where p.id = auth.uid() and v.active
  limit 1;
$$;

-- transcripts are scoped to their creator; operator has the full desk (audit H4)
CREATE OR REPLACE FUNCTION public.owns_thread(t uuid)
 RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path TO 'public'
AS $$
  select exists (
    select 1 from public.chat_threads ct
    join public.profiles p on p.id = auth.uid()
    where ct.id = t and (ct.created_by = p.email or p.role = 'operator')
  );
$$;

-- per-user daily cap for the paid endpoints; caller email from JWT (audit H2/H3)
CREATE OR REPLACE FUNCTION public.check_and_bump_usage(p_kind text, p_limit integer)
 RETURNS boolean LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public'
AS $$
declare v_email text; v_n integer;
begin
  select email into v_email from public.profiles where id = auth.uid();
  if v_email is null then return false; end if;
  insert into public.api_usage (email, kind, n) values (v_email, p_kind, 1)
  on conflict (email, kind, day) do update set n = public.api_usage.n + 1
  returning n into v_n;
  return v_n <= p_limit;
end; $$;

-- sign-in role resolution (vendor roster > allowlist > pending; audit-hardened
-- default is 'pending', never 'owner')
CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public'
AS $$
begin
  insert into public.profiles (id, email, role)
  values (new.id, new.email,
    case
      when exists (select 1 from public.vendors v where v.email = lower(new.email) and v.active) then 'vendor'
      when exists (select 1 from public.authorized_emails a where a.email = lower(new.email)) then
        (select a.role from public.authorized_emails a where a.email = lower(new.email))
      else 'pending'
    end)
  on conflict (id) do nothing;
  return new;
end; $$;

-- ── RLS POLICY MATRIX (current live state; USING/CHECK expressions) ──────────
-- public.profiles       SELECT (auth.uid()=id) | SELECT is_operator() | UPDATE is_operator()
--                       (no self-INSERT/UPDATE → no self-escalation; trigger inserts)
-- public.property_state SELECT is_owner_or_operator() | INSERT/UPDATE/DELETE is_operator()
-- public.authorized_emails ALL is_operator()
-- public.vendors        SELECT is_owner_or_operator() | SELECT (id=current_vendor_id()) | ALL is_operator()
-- public.vendor_log     INSERT (is_owner_or_operator() OR is_vendor()) | SELECT is_operator()
-- public.safe_log       INSERT is_owner_or_operator() | SELECT is_operator()
-- public.chat_threads   SELECT (is_operator() OR own) | INSERT (own) | DELETE is_operator()
-- public.chat_messages  SELECT owns_thread() | INSERT owns_thread() | DELETE is_operator()
-- public.api_usage      SELECT is_operator() (writes only via check_and_bump_usage)
--
-- storage.objects (all buckets private; file_size_limit 25MB on all four):
--   assets      SELECT is_owner_or_operator() | INSERT/UPDATE/DELETE is_operator()
--   documents   SELECT is_owner_or_operator() | INSERT/UPDATE/DELETE is_operator()
--   safe        SELECT is_owner_or_operator() | INSERT/UPDATE/DELETE is_operator()
--   vendor-docs SELECT/INSERT foldername[1]=current_vendor_id() | ALL is_operator()
--
-- ── MIGRATION HISTORY (Supabase, authoritative) ─────────────────────────────
--   20260620122933 otb_core_schema           20260708111850 vendor_portal_p3
--   20260620122947 otb_storage_assets        20260708181505 agent_desk_transcripts
--   20260620123019 harden_definer_functions  20260708211923 owner_email_allowlist
--   20260707173305 documents_bucket_policies  20260710182827 scope_transcripts_and_bucket_caps
--   20260707194616 owner_safe_bucket_log      20260710182958 api_usage_rate_limit
