(()=>{
const q=s=>document.querySelector(s), qa=s=>[...document.querySelectorAll(s)];
const chips=qa('[data-color-role]');let selected='brand-terra-strong';
function color(role){return getComputedStyle(document.documentElement).getPropertyValue('--cc-color-'+role).trim().toUpperCase()}
function refresh(){chips.forEach(b=>{const value=color(b.dataset.colorRole);b.querySelector('.chip-value').textContent=value;b.setAttribute('aria-label',b.dataset.colorName+', '+value+', inspect color');b.setAttribute('aria-pressed',String(b.dataset.colorRole===selected))});const b=chips.find(b=>b.dataset.colorRole===selected);q('#color-name').textContent=b.dataset.colorName;q('#color-description').textContent=b.dataset.colorDescription;q('#color-token').textContent='--cc-color-'+selected;q('#color-hex').value=color(selected)}
chips.forEach(b=>b.addEventListener('click',()=>{selected=b.dataset.colorRole;refresh();q('#copy-feedback').textContent=b.dataset.colorName+' selected. Copy its value below.'}));
new MutationObserver(()=>{refresh();q('#copy-feedback').textContent='Color values updated for the current appearance.'}).observe(document.documentElement,{attributes:true,attributeFilter:['data-theme']});matchMedia('(prefers-color-scheme:dark)').addEventListener('change',refresh);refresh();
q('#copy-color').addEventListener('click',async()=>{const button=q('#copy-color'),input=q('#color-hex'),value=input.value;button.disabled=true;button.textContent='Copying…';let copied=false;try{if(navigator.clipboard){await Promise.race([navigator.clipboard.writeText(value),new Promise((_,reject)=>setTimeout(()=>reject(new Error('Clipboard unavailable')),800))]);copied=true}}catch{}if(!copied){input.focus();input.select();try{copied=document.execCommand('copy')}catch{}}button.disabled=false;button.textContent='Copy hex';q('#copy-feedback').textContent=copied?'Copied '+value+'.':'Select the highlighted value and copy it with Ctrl+C or Command+C.'});
const depthText={flat:'Flat: the default for documents, tables and uninterrupted reading.',raised:'Raised: use for a selected specimen, an interactive tile or a panel that sits above the page.',floating:'Floating: reserve for menus, popovers and dialogs that sit above the current task.'};qa('input[name=depth]').forEach(r=>r.addEventListener('change',()=>{q('#depth-object').dataset.depth=r.value;q('#depth-description').textContent=depthText[r.value];q('#depth-token').textContent=r.value==='flat'?'--cc-elevation-none':'--cc-shadow-'+r.value}));
const search=q('#guide-search'),sections=qa('[data-guideline]'),links=qa('[data-spec-link]');function filter(){const term=search.value.trim().toLowerCase();let count=0;sections.forEach((s,i)=>{const show=!term||s.textContent.toLowerCase().includes(term);s.hidden=!show;links[i].hidden=!show;if(show)count++});q('#search-count').textContent=term?count+' matching guidelines':sections.length+' guidelines';q('#clear-search').hidden=!term;q('#empty-search').hidden=count!==0}search.addEventListener('input',filter);q('#clear-search').addEventListener('click',()=>{search.value='';filter();search.focus()});
const rail=q('.guide-rail'),toggle=q('.mobile-index-toggle');toggle.addEventListener('click',()=>{const open=rail.dataset.open!=='true';rail.dataset.open=String(open);toggle.setAttribute('aria-expanded',String(open));toggle.querySelector('span').textContent=open?'−':'+'});q('.guide-rail').addEventListener('click',e=>{if(e.target.closest('a')&&innerWidth<=900){rail.dataset.open='false';toggle.setAttribute('aria-expanded','false');toggle.querySelector('span').textContent='+';const target=q(e.target.closest('a').getAttribute('href'));if(target){target.setAttribute('tabindex','-1');target.focus({preventScroll:true})}}});
const observer=new IntersectionObserver(entries=>{const candidate=entries.filter(e=>e.isIntersecting).sort((a,b)=>a.boundingClientRect.top-b.boundingClientRect.top)[0];if(candidate){qa('.guide-rail a[aria-current]').forEach(a=>a.removeAttribute('aria-current'));const a=q('.guide-rail a[href="#'+candidate.target.id+'"]');if(a)a.setAttribute('aria-current','location')}},{rootMargin:'-110px 0px -60% 0px',threshold:0});qa('.portal-section,.portal-intro,.guide-section,#specification').forEach(s=>observer.observe(s));
let timer;const field=q('#demo-name'),hint=q('#demo-hint'),status=q('#demo-status'),submit=q('#demo-submit');function reset(){clearTimeout(timer);field.value='';field.removeAttribute('aria-invalid');field.classList.remove('demo-field-error');hint.classList.remove('error');hint.textContent='Use a short, descriptive name.';status.textContent='';submit.disabled=false;submit.textContent='Preview save';q('#demo-form').removeAttribute('aria-busy')};q('#demo-reset').addEventListener('click',()=>{reset();field.focus()});field.addEventListener('input',()=>{if(field.value.trim()){field.removeAttribute('aria-invalid');field.classList.remove('demo-field-error');hint.classList.remove('error');hint.textContent='Use a short, descriptive name.'}});q('#demo-form').addEventListener('submit',e=>{e.preventDefault();if(!field.value.trim()){field.setAttribute('aria-invalid','true');field.classList.add('demo-field-error');hint.classList.add('error');hint.textContent='Enter a project name to continue.';status.textContent='Project name is required.';field.focus();return}submit.disabled=true;submit.textContent='Saving…';q('#demo-form').setAttribute('aria-busy','true');status.textContent='Previewing the saving state…';timer=setTimeout(()=>{submit.disabled=false;submit.textContent='Preview save';q('#demo-form').removeAttribute('aria-busy');status.textContent='Success preview: “'+field.value.trim()+'”. Nothing was stored.'},650)});
})();