"""Meter workbook -> src/data/meters.json (A-1 site register, 2026-09-24).

Source (Tier 1, CLAUDE.md "Rev_Belle_Realty_Arnould_Blvd_Property.xlsx (meters)"):
  G:/My Drive/00 OTB/01 Belle Files to be placed/Center Infrastructure/
  Water Meters & Electric Meters/Rev Belle Realty Arnould Blvd Property.xlsx
One record per physical meter number. Water meters carry the workbook's
"APPROXIMATE LOCATION" note, mapped to the city-meter cluster digitized from
Water Shutoff Clusters.png (tools/digitize-site-sources.py uses the same ids).
Electric meters have no location note -> the register places them at the unit.

  python tools/build-meters.py [path-to-xlsx]
"""
import json, sys
from pathlib import Path
import openpyxl

ROOT = Path(__file__).resolve().parents[1]
SRC = Path(sys.argv[1]) if len(sys.argv) > 1 else Path(
    "G:/My Drive/00 OTB/01 Belle Files to be placed/Center Infrastructure/"
    "Water Meters & Electric Meters/Rev Belle Realty Arnould Blvd Property.xlsx")

# workbook location note -> digitized city-meter cluster id
CLUSTER = {
    "Right of 149": "mclu-149", "Back Right of 149": "mclu-149",
    "Behind 131": "mclu-131", "Behind 119": "mclu-119", "Behind 109": "mclu-109",
    "Behind 107": "mclu-107", "Behind 105": "mclu-105", "Grass near Blvd": None,
}


def unit_key(v):
    s = str(v).strip().replace("HOUSE ", "")
    if s.endswith(".0"):
        s = s[:-2]
    return {"131-133": "131"}.get(s, s)


def main():
    ws = openpyxl.load_workbook(SRC, data_only=True).active
    rows = list(ws.iter_rows(values_only=True))
    out = []
    for r in rows[1:]:
        if not r or r[0] is None:
            continue
        unit_raw, account, emeter, wmeter, size, loc = (r + (None,) * 6)[:6]
        unit = unit_key(unit_raw)
        house = str(unit_raw).startswith("HOUSE")
        acct = (str(account).strip() if account else "") + (" (house meter)" if house else "")
        note = "combined 131/133 space" if str(unit_raw) == "131-133" else None
        if emeter:
            out.append({"id": "em-" + str(emeter).lower(), "kind": "emeter", "number": str(emeter), "unit": unit,
                        "account": acct, **({"note": note} if note else {})})
        if wmeter:
            loc = (loc or "").strip()
            rec = {"id": "wm-" + str(wmeter).lower(), "kind": "wmeter", "number": str(wmeter), "unit": unit,
                   "account": acct, "size": str(size or "").replace("'", '"').strip(), "location": loc or "?"}
            if CLUSTER.get(loc):
                rec["cluster"] = CLUSTER[loc]
            if note:
                rec["note"] = note
            out.append(rec)
    ids = [m["id"] for m in out]
    assert len(ids) == len(set(ids)), "duplicate meter numbers"
    doc = {
        "_readme": "Meter register for the A-1 site register. Generated by tools/build-meters.py from "
                   "'Rev Belle Realty Arnould Blvd Property.xlsx' - edit the workbook, not this file. "
                   "Account names are the workbook's (may lag the current rent roll).",
        "source": SRC.name,
        "counts": {"wmeter": sum(m["kind"] == "wmeter" for m in out), "emeter": sum(m["kind"] == "emeter" for m in out)},
        "meters": out,
    }
    (ROOT / "src/data/meters.json").write_text(json.dumps(doc, indent=1, ensure_ascii=False) + "\n", encoding="utf-8")
    print("meters.json:", doc["counts"])


if __name__ == "__main__":
    main()
