# A-8 rooftop equipment from the frozen satellite base (2026-10-02, operator: "the actual location of the
# hvac systems"). Fits a plan-px -> WGS84 affine from the 27 suite footprints (footprints-geo.json vs
# geometry.json units), resamples public/OTB-sat-base.jpg into the A-1 plan frame, and finds dark blobs on
# the white roofs (inside each suite, clear of the mansard band). Clusters within ~1.9 ft merge into one
# item; >= 3.5 ft across = rooftop unit, smaller = exhaust fan / curb item.
# Output: src/data/roof-equipment.json.   Requires numpy + scipy + Pillow:  python tools/detect-roof-equipment.py
import json, math, pathlib
import numpy as np
from PIL import Image
from scipy import ndimage as nd

ROOT = pathlib.Path(__file__).resolve().parents[1]
g = json.loads((ROOT / "src/data/geometry.json").read_text())
fp = json.loads((ROOT / "src/data/footprints-geo.json").read_text())
sb = json.loads((ROOT / "src/data/sat-base.json").read_text())

P, L = [], []
for f in fp["features"]:
    u = f["properties"]["unit"]
    if u not in g["units"]: continue
    r = g["units"][u]; P.append([r["x"] + r["w"] / 2, r["y"] + r["h"] / 2])
    L.append(np.array(f["geometry"]["coordinates"][0][:-1]).mean(0))
P, L = np.array(P), np.array(L)
coef = np.linalg.lstsq(np.c_[P, np.ones(len(P))], L, rcond=None)[0]
fit_err_m = float(np.abs(np.c_[P, np.ones(len(P))] @ coef - L).max(0)[0] * 96000)

(lon0, lat0), (lon1, _), _, (_, lat1) = sb["coordinates"]
img = np.asarray(Image.open(ROOT / "public/OTB-sat-base.jpg").convert("RGB")).astype(np.float32)
H, W = img.shape[:2]
S, Y0 = 2, -310
X, Y = np.meshgrid(np.arange(0, 1480, 1 / S), np.arange(Y0, 700, 1 / S))
lo = X * coef[0, 0] + Y * coef[1, 0] + coef[2, 0]; la = X * coef[0, 1] + Y * coef[1, 1] + coef[2, 1]
merc = lambda a: np.log(np.tan(np.pi / 4 + np.radians(a) / 2))
u = (lo - lon0) / (lon1 - lon0) * W; v = (merc(lat0) - merc(la)) / (merc(lat0) - merc(lat1)) * H
u0 = np.clip(u.astype(int), 0, W - 1); v0 = np.clip(v.astype(int), 0, H - 1)
gray = img[v0, u0].mean(2)

roof = np.zeros(gray.shape, bool)
for unit, r in g["units"].items():
    x0, y0, x1, y1 = r["x"] + 3, r["y"] + 3, r["x"] + r["w"] - 3, r["y"] + r["h"] - 3
    if r["y"] < 200: y1 = r["y"] + r["h"] - 14   # long building: clear of the storefront mansard
    else: x0 = r["x"] + 12                       # short building: clear of the west mansard
    roof[int((y0 - Y0) * S):int((y1 - Y0) * S), int(x0 * S):int(x1 * S)] = True
dark = nd.binary_opening(roof & (gray < 185), iterations=1)
lab, _ = nd.label(nd.binary_dilation(dark, iterations=7) & roof)
items = []
for i, sl in enumerate(nd.find_objects(lab), 1):
    m = (lab[sl] == i) & dark[sl]; area = int(m.sum())
    if area < 25 or area > 3500: continue
    ys, xs = np.nonzero(m); h = ys.max() - ys.min() + 1; w = xs.max() - xs.min() + 1
    if max(w, h) / max(1, min(w, h)) > 5: continue
    cy, cx = nd.center_of_mass(m)
    px, py = (cx + sl[1].start) / S, (cy + sl[0].start) / S + Y0
    unit = next((k for k, r in g["units"].items() if r["x"] <= px <= r["x"] + r["w"] and r["y"] <= py <= r["y"] + r["h"]), None)
    wf, hf = w / S / 1.8515, h / S / 1.8866
    items.append({"point": [round(px, 1), round(py, 1)], "unit": unit, "sizeFt": [round(wf, 1), round(hf, 1)],
                  "kind": "rtu" if max(wf, hf) >= 3.5 else "fan"})
items.sort(key=lambda o: (o["point"][1] > 200, o["point"][0], o["point"][1]))
doc = {"_readme": "Rooftop HVAC and small curb equipment located on the frozen Esri z19 satellite base (sat-base.json) "
       "registered to A-1 through the 27 suite footprints. Positions are where the imagery shows them (vintage of "
       "the base); units added or moved since then are not here. Generated by tools/detect-roof-equipment.py.",
       "fitMaxErrorM": round(fit_err_m, 2), "count": len(items),
       "rtus": sum(1 for o in items if o["kind"] == "rtu"), "items": items}
(ROOT / "src/data/roof-equipment.json").write_text(json.dumps(doc, indent=1) + "\n")
print(len(items), doc["rtus"], "fit err m", doc["fitMaxErrorM"])
